version: "2"

services:  
  db:
    image: postgres:9.6 
    env_file: 
        - .env
    volumes:
        - ./db/pgdata:/var/lib/postgresql/data/pgdata

  web:
    build:
        context: ./Cride
        dockerfile: Dockerfile
    env_file: 
        - .env
    
