# Generated by Django 3.0 on 2021-07-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
    ]
