# Generated by Django 3.0 on 2021-07-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0002_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(default='', max_length=12),
        ),
    ]
